'use client';

import { useSession } from 'next-auth/react';
import dynamic from 'next/dynamic';
import Link from 'next/link';

const Bell = dynamic(() => import('lucide-react').then((mod) => mod.Bell), { ssr: false });
const Settings = dynamic(() => import('lucide-react').then((mod) => mod.Settings), { ssr: false });

export default function Navbar() {
  const { data: session } = useSession();

  return (
    <header className="sticky top-0 left-0 w-full z-40 shadow-sm flex items-center justify-start px-6 h-16 bg-white dark:bg-[#23272f]">
      <div className="flex items-center gap-4">
        <button className="p-2 rounded-full hover:bg-[#f6b93b] transition">
          {Bell && <Bell size={20} className="text-[#23423a] dark:text-[#f6b93b]" />}
        </button>
        <Link href="/settings" className="p-2 rounded-full hover:bg-[#f6b93b] transition">
          {Settings && <Settings size={20} className="text-[#23423a] dark:text-[#f6b93b]" />}
        </Link>
      </div>
    </header>
  );
}

/*
  Note on Hydration Errors:
  The "hydration error" often occurs when the server-rendered HTML (from Next.js)
  does not exactly match the HTML generated by the client-side React code.
  Third-party scripts, like browser extensions (e.g., Grammarly), can inject
  elements into the DOM after the page loads but before React hydrates,
  causing this mismatch.

  While dynamically importing icons in this Navbar helps ensure this component
  is client-rendered, if the Grammarly error persists, it's likely due to
  Grammarly itself modifying the DOM. For debugging, you might consider
  disabling such extensions temporarily to see if the hydration error resolves.
*/